version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  producer:
    build: ./producer
    container_name: producer
    depends_on:
      - rabbitmq

  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - rabbitmq

volumes:
  rabbitmq_data:
